# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Continuous Integration - Github Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Maven JAR
      run: mvn -B package --file pom.xml

    - name: Build Docker Compose
      working-directory: ./api-rest-aws
      run: docker compose build

    - name: Push to Docker Hub container registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-rest-aws:latest ${{ secrets.DOCKER_USERNAME }}/api-rest-aws:${{ github.run_id }}

        docker push ${{ secrets.DOCKER_USERNAME }}/api-rest-aws:${{ github.run_id }}      
        docker push ${{ secrets.DOCKER_USERNAME }}/api-rest-aws:latest
